name: sync-templates-json-to-s3
on:
  push:
    branches: ['main']
    paths: ['config/templates.json']
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Gonna sync templates.json to s3"
