name: sync-templates-json-to-s3
on:
  push:
    branches:
      - main
    paths:
      - config/templates.json
jobs:
  sync-templates-in-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Templates to s3
        run: |
          aws s3 cp \
            config/templates.json s3://${{ secrets.S3_CDN_DEPLOY_BUCKET_NAME }}/${{ github.event.repository.name }}/${{ needs.calculate-tag.outputs.tag }}/ \
